### ISSUE TITLE
有内存泄漏问题

### ISSUE THREAD

**Issue by congwiny** [fmtjava/LiveDataBus#1]
https://github.com/fmtjava/LiveDataBus/blob/b6e8e0f94e527617f19cb5bbb23ff525d8f8b521/LiveDataBus/src/main/java/com/fmt/livedatabus/LiveDataBus.kt#L125

这么改就好了：
```
eventTypeList.forEach { eventType ->
                            if (getLifecycleOwners(eventType).isEmpty()) {
                                eventMap.remove(eventType)
                                lifecycleMap.remove(eventType)
                            } else {
                                lifecycleMap[eventType]?.remove(owner)
                            }
                        }
```

**Comment by fmtjava** [comment]
<img width="502" alt="image" src="https://user-images.githubusercontent.com/16126424/184610955-37e5c48f-4791-400e-ad57-b1e592f8909e.png">
这里已经移除了

**Comment by congwiny** [comment]
> <img alt="image" width="502" src="https://user-images.githubusercontent.com/16126424/184610955-37e5c48f-4791-400e-ad57-b1e592f8909e.png">
> 
> 这里已经移除了

@fmtjava 您可以再用leakcanary试试，确实有内存泄漏问题。
测试用例是打开多个Activity或Fragment注册相同的eventName，然后反复进入退出。。

**Comment by congwiny** [comment]
![微信图片_20220906114607](https://user-images.githubusercontent.com/9621271/188542905-e790f97d-d108-4b2a-ad67-46cd619807bd.jpg)
